spring:
  datasource:
    url: ${DATABASE_HOST}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: ${PORT}
  error:
    include-message: always